[tools]
node    = "lts"
python  = "3.12"
"npm:@vscode/vsce" = "latest"

[settings]
experimental = true

[env]
# mise 管理の Python を uv のデフォルト Python として使う
UV_PYTHON = "{{ mise exec python -- python --version | head -c 20 }}"
